### ISSUE TITLE
debugpy PermissionError WindowsApps (Blender installed from store)

### ISSUE THREAD

**Issue by qwabra** [JacquesLucke/blender_vscode#105]
debugpy PermissionError C:\\Program Files\\WindowsApps\\BlenderFoundation ...

**Comment by qwabra** [comment]
blender `scripts` folder
https://blender.stackexchange.com/a/5289/96645

and manual install
https://stackoverflow.com/a/19404371/4794368

looks like working

**Comment by LorenzWieseke** [comment]
First, did you try running vs code as admin ?
Second, did you try to install debugpy separately via pip ? Did you enable allow Modify external python ?

![image](https://user-images.githubusercontent.com/29607121/127635247-75c00983-d1b0-454c-bda6-1ace69345895.png)

**Comment by qwabra** [comment]
> running vs code as admin
1. it is strange, don`t do that
2. i think admin also haven`t permitions to 'WindowsApps'

> Modify external python
- it is Blender internal python

**Comment by Mateusz-Grzelinski** [comment]
I just checked: `C:\Program Files\WindowsApps` is special windows folder which does not allow user to interact with it at all.
it can be fixed only by 177 or using portable version of blender.
