### ISSUE TITLE
When I try to run blender with ctrl+shift+P it turns off.

### ISSUE THREAD

**Issue by seunghwa9118** [JacquesLucke/blender_vscode#108]
When I try to run blender with ctrl+shift+P it turns off. What should i do?
my os version : ubuntu 18.04, blender version :2.83 10
![스크린샷, 2021-09-13 18-19-26](https://user-images.githubusercontent.com/68892551/133058986-a81238f0-8a53-461a-b689-ea9259a1a0e6.png)

**Comment by monkho** [comment]
> When I try to run blender with ctrl+shift+P it turns off. What should i do? my os version : ubuntu 18.04, blender version :2.83 10 ![스크린샷, 2021-09-13 18-19-26](https://user-images.githubusercontent.com/68892551/133058986-a81238f0-8a53-461a-b689-ea9259a1a0e6.png)

I have the same problem in Windows 10 with blender 2.93

**Comment by wooistxx** [comment]
I have same bug in win10 with blender 2.93.4, howerver, in my manjaro with same blender, all is fine. Any help to solve the question?

**Comment by Mateusz-Grzelinski** [comment]
I asked on blender chat about this.

Hi. I noticed that in blender 2.83, sys.executable is not reported correctly. Is it a bug or a feature?

```python
>>> import sys
>>> sys.executable
'C:\\Users\\grzel\\BlenderProjects\\blender-2.83\\blender.exe'
>>> bpy.app.version
(2, 83, 19)
```

```python
>>> sys.executable
'c:\\Users\\grzel\\BlenderProjects\\blender-2.93\\2.93\\python\\bin\\python.EXE'
>>> bpy.app.version
(2, 93, 8)
```
LazyDodo:
it always used to point to the blender executable messing up multiprocessing, got fixed somewhere in the 2.90/91 timeframe
ah found it [developer.blender.org/rB52b38d9c3d84485385d5bc2e58f16c5acfaca9b7](https://developer.blender.org/rB52b38d9c3d84485385d5bc2e58f16c5acfaca9b7)
up to [PhilippOeser]() to decide if 2.83 is still eligible for a backport (i think there were a few commits that dealt with this actually)

**Comment by Mateusz-Grzelinski** [comment]
also duplicate https://github.com/JacquesLucke/blender_vscode/issues/93

**Comment by Mateusz-Grzelinski** [comment]
this issue still occurs on blender 2.80 2.90, 2.93. I will try to look at it when i have time

**Comment by Mateusz-Grzelinski** [comment]
`sys.exit` behaviour was changed https://projects.blender.org/blender/blender/commit/489408e8d37a35b19d08354f880d00f85422d591  but executing in text editor will stil close blender, this is not someting that we can adress in this extension
