### ISSUE TITLE
No workspace folder found

### ISSUE THREAD

**Issue by DotBow** [JacquesLucke/blender_vscode#11]
Hi @JacquesLucke!
Have an error executing Blender:start command on existing add-on. Does this related to the blender's config folder?
OS Windows 10. 
![default](https://user-images.githubusercontent.com/32243930/49683958-241b6f80-fae6-11e8-9f7a-4b287a88151a.png)

**Comment by DotBow** [comment]
Well, after I opened add-on folder (not a single script file) everything seems to work! Sorry for posting as an issue!

**Comment by JacquesLucke** [comment]
You are in fact right that this is an issue. For some reason I could not figure out how to start a task in vs code, when no workspace folder is open. Seems like every running task (e.g. an instance of blender) is connected to some workspace folder.

There is an option to make "global" tasks, but that did not work..

So for now you have to have some folder open :)

**Comment by DotBow** [comment]
Common practice on coding something is having a project folder with sources... It seems logical that it is not working, is it?

**Comment by JacquesLucke** [comment]
Yes, but it should still be possible to start Blender or so, when no project is open. Otherwise people, like you (and me as well), get confused.

But yeah, it's not a big deal.

**Comment by TombstoneTumbleweedArt** [comment]
Thank you SOOO much! I find myself here in 2022 with _precisely_ the same scenario - and the exact same solution works.  Github Time Capsule of Perfect Solution = Happy Brain Chemicals.

**Comment by nish-sv** [comment]
Hi @TombstoneTumbleweedArt and @DotBow  , I am facing the same error when I run blender start in VS code. The above mentioned solution is not clear. Can you provide more clarification about the solution

**Comment by CGArtPython** [comment]
@nish-sv 
I also hit this issue sometimes 😔

Decided to record a quick fix
https://www.youtube.com/shorts/K9Ft10KuLCA
