### ISSUE TITLE
If this extension is not actively developed anymore, what would be the sugested way to develop addons for blender?

### ISSUE THREAD

**Issue by maybites** [JacquesLucke/blender_vscode#110]
cheers

martin

**Comment by josuemtzmo** [comment]
This extension still works in Blender 3.0.0, so I will suggest continuing using it.

**Comment by Mateusz-Grzelinski** [comment]
So far (2024) this extensions is still working. If it ever becomes obsolete, those are your options:

- for code completion use `fake-bpy-modules` (any editor)
- for debug support you can use:
  - either this extension for vs code or
  - https://code.blender.org/2015/10/debugging-python-code-with-pycharm/ for pycharm or 
  - or custom setup that can connect to remote debugger 
    - eclipse example: https://stackoverflow.com/questions/12975769/debug-blender-python-in-eclipse-and-pydev 
    - vs code remote debugging example (without this extension) https://stackoverflow.com/questions/73378057/how-to-debug-remote-python-script-in-vs-code

I have not heard about other options.
