### ISSUE TITLE
Enable setting "justMyCode": false for Python debugging

### ISSUE THREAD

**Issue by johschmitz** [JacquesLucke/blender_vscode#123]
VS Code has a new option "justMyCode" for the debugger.

See https://stackoverflow.com/questions/53594900/visual-studio-code-python-debugging-step-into-the-code-of-external-functions

It would be nice if there could be a way of setting this to true for the extension such that one can debug into Python libraries which are used by a Blender add-on.

**Comment by johschmitz** [comment]
Here is some additional information and suggestions from the Microsoft Team regarding this issue:
https://github.com/microsoft/debugpy/issues/938

**Comment by kugelrund** [comment]
With your pull request not being merged yet, did you happen to find any workaround for this @johschmitz ?

**Comment by johschmitz** [comment]
@kugelrund yes, the workaround is to go to your local VS Code extension directory and just directly modify the code in there. Then it should work.

**Comment by satabol** [comment]
if you search what to do to enable this feature manually:
https://github.com/JacquesLucke/blender_vscode/pull/124/files

**Comment by JacquesLucke** [comment]
Fixed as part of 6786cb42041e2179dc5589c382a7781073ea8d00.
