### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GithubMingEnter** [JacquesLucke/blender_vscode#129]
- Issue Type: `Performance`
- Extension Name: `blender-development`
- Extension Version: `0.0.17`
- OS Version: `Linux x64 5.4.0-122-generic`
- VS Code version: `1.69.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/JacquesLucke.blender-development-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Griperis** [comment]
Hi @GithubMingEnter, 
the file you attached isn't available here. Can you please describe in more detail what part of the extension was slow, or when the performance drop happened?
