### ISSUE TITLE
ValueError: Compressor 'zlib1' already registered.

### ISSUE THREAD

**Issue by guanyy99** [JacquesLucke/blender_vscode#141]
```
Traceback (most recent call last):
  File "E:/python/Lib/site-packages/joblib/numpy_pickle.py", line 41, in <module>
    register_compressor('zlib1', ZlibCompressorWrapper())
  File "E:\python\lib\site-packages\joblib\compressor.py", line 76, in register_compressor
    .format(compressor_name))
ValueError: Compressor 'zlib1' already registered.

Process finished with exit code 1
```

how to solve this issue?

**Comment by guanyy99** [comment]
# Register supported compressors
register_compressor('zlib1', ZlibCompressorWrapper())
register_compressor('gzip1', GzipCompressorWrapper())
register_compressor('bz21', BZ2CompressorWrapper())
register_compressor('lzma1', LZMACompressorWrapper())
register_compressor('xz1', XZCompressorWrapper())
register_compressor('lz41', LZ4CompressorWrapper())

**Comment by Mateusz-Grzelinski** [comment]
I have no idea. Please provide more information.
