### ISSUE TITLE
Blender 3.6.4 crashes pushing undo step from script

### ISSUE THREAD

**Issue by Andrej730** [JacquesLucke/blender_vscode#149]
Addon version: v0.0.18

Way to reproduce:
1. VS Code -> Start Blender
2. VS Code -> Run script below

Undo steps are improtant for scripts so that scripts can be reverted after they were executed, really useful testing stuff. 
```python
import bpy
from mathutils import Matrix
from math import pi

bpy.ops.ed.undo_push(message="Script Call")

bpy.context.object.matrix_world = Matrix.Rotation(pi/15, 4, "Z")
```

**Comment by Mateusz-Grzelinski** [comment]
This script seems to work on blender 4.2.1, 3.6.14 and vs code version 0.22

**Comment by Andrej730** [comment]
No idea what it was but can confirm it works on Blender 4.2.1.
