### ISSUE TITLE
Blender 3.6 and blender development

### ISSUE THREAD

**Issue by Pocho32** [JacquesLucke/blender_vscode#150]
i'm quite new to this so i dunno if i'm doing this the right way. but i have a couple of questions:

1) i'm using vs code and blender development to develop an add on for blender 3.6 but on the info page of blender development it says that only blender 2.8 is supported. do i have to change my version of blender to develop my add on?

2) for this question i already found my answer on my own so i guess there is only one question :DD

**Comment by ppinter1** [comment]
Not knowing what your platform is (Mac/Linux/Win), or even if it matters, I can attest that Jacques' VS Code extension v0.0.18 from April this year seems to work fine with Blender 3.6.5.

I've been using it to tinker with a custom add on for some years now, on both Linux and Mac.

**Comment by Pocho32** [comment]
yeah sorrry i forgot to mention that i'm working on windows. thanks though for the help and for the answer
