### ISSUE TITLE
Does this work for Blender 4.0?

### ISSUE THREAD

**Issue by AhmedSalih3d** [JacquesLucke/blender_vscode#153]
Hello!

I tried to give this a shot for Blender 4.0, but unfortunately it does not seem to run out of the box.

Has anyone else managed to?

Kind regards

**Comment by JamesLedger** [comment]
Hi, I've got it working fine with Blender 4.1 alpha using v0.0.18.

What issue are you having?

**Comment by AhmedSalih3d** [comment]
Hi!

Using the Blender 4.0 LTS version and having a script with just `print("Hello")` I see the following:

` in run_script_action
    bpy.ops.dev.run_script(context, filepath=path)
  File "c:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "c:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported`

Did you see this one too?

It works fine with Blender 3.6, without that error

**Comment by roguesleipnir** [comment]
> ` in run_script_action bpy.ops.dev.run_script(context, filepath=path) File "c:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__ C_exec, C_undo = _BPyOpsSubModOp._parse_args(args) File "c:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args raise ValueError("1-2 args execution context is supported") ValueError: 1-2 args execution context is supported`

I'm also trying to get it to work with today's 4.0 release, I'm experiencing the same error.
Attaching 3.6 also still works.

**Comment by CGArtPython** [comment]
This issue is connected to a breaking change that was introduced in Blender's 4.0 Python API update

https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API
> Blender Operators (bpy.ops)
> Remove the context override argument to bpy.ops in favor of context.temp_override(..) ([ac263a9bce](https://projects.blender.org/blender/blender/commit/ac263a9bce53e190d07d679a058a230e91e722be))

In `.\pythonFiles\include\blender_vscode\operators\script_runner.py` instead of this 
`bpy.ops.dev.run_script(context, filepath=path)`

We need to use this
```
    with bpy.context.temp_override(**context):
        bpy.ops.dev.run_script(filepath=path)
```

I'll submit a PR soon.

**Comment by filibis** [comment]
Hi @CGArtPython , I'm still having problem when starting Blender 4.0.1, will this commit change automatically apply to the extension? Or do I need to manually update something?
![image](https://github.com/JacquesLucke/blender_vscode/assets/26340322/5592b3bb-9ff0-4a2e-8482-e4685367da41)

**Comment by Frutto-Hub** [comment]
> Hi @CGArtPython , I'm still having problem when starting Blender 4.0.1, will this commit change automatically apply to the extension? Or do I need to manually update something? ![image](https://private-user-images.githubusercontent.com/26340322/285210487-5592b3bb-9ff0-4a2e-8482-e4685367da41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzAyMzYsIm5iZiI6MTcwMTc2OTkzNiwicGF0aCI6Ii8yNjM0MDMyMi8yODUyMTA0ODctNTU5MmIzYmItOWZmMC00YTJlLTg0ODItZTQ2ODUzNjdkYTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzZiMDZiMzRiOGUyOTQ1MzNhZjdiMTkxNzQxYzgyODBhNmMwYzI5NzM4NGYzNmQ3MmRlZGY4YWU4YjFiMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVdvigBugEgoZY-UTQML0rsrh83u82xLTMze_Svre-w)

Hi, i am havaing the same issue. Seems like this issue is only fixed in this repo, but not in extension itself. You can manually add fix to `script_runner.py` file 
![not_updated_in_extension](https://github.com/JacquesLucke/blender_vscode/assets/17603456/1b272b10-1666-4ae4-b46c-2bf276740484)
Here is how it should be: 
![how to fix](https://github.com/JacquesLucke/blender_vscode/assets/17603456/71a6ddfd-0ff9-45f4-ab85-e909669f5c28)

**Comment by Frutto-Hub** [comment]
@JacquesLucke, please consider updating the extension itself

**Comment by JacquesLucke** [comment]
The updated extension is now live.
