### ISSUE TITLE
Using "Blender Start" terminated with exit code: 3221225477 after reading userpref.blend that was altered by this extension

### ISSUE THREAD

**Issue by Valery-AA** [JacquesLucke/blender_vscode#156]
The terminal process "e:\SteamLibrary\steamapps\common\Blender\blender.exe '--python', 'c:\Users\User\.vscode\extensions\jacqueslucke.blender-development-0.0.19\pythonFiles\launch.py'" terminated with exit code: 3221225477.

As Soon as i launched the command blender has been fully unable to launch in any way, I've reinstalled and manually deleted everything belonging to the previous install to see if it was dependent on something else, it is not

it's crashing with an ACCESS_VIOLATION that i don't know where it is even from as i was developing the add-on just fine with no errors and attempted to use this method only after someone suggested it to me
i have no way to edit the userprefs.blend file as any other blender version i have installed won't start either
there are 2 years of tweaks and changes on that file i can't just delete it
running commands from VS should not edit directly userprefs.blend
the last message i saw on the first launch was it was updating userprefs after 3 py packages where installed

**the process was simply:**
launch vs code > open my add-on folder > use "blender start" from VSCode F1 Menu > select the .exe > launch
after doing these steps i have no been able launch blender from anywhere

related issue: blender/blender-addons#61443
it was supposed to be fixed, seems it isn't

update: removing literally every file from the folders including userprefs still crashes with no resolution and running any debug bat file will always result in an empty log

**Comment by Mateusz-Grzelinski** [comment]
I was just browsing the issues and saw this. Sorry that it happened to you, it sounds bizzare... 
Is this still relevant for you? The only thing I can think of maybe you can share a user prefs blend files for some experiments for me

**Comment by Valery-AA** [comment]
i don't have a lot of testing right after this i factory installed blender and made my own tool directly in the addon, but from what i could tell, the reason was when creating an addon custom properties where written to the userprefs due to my addon, it seemed tho for some reason the extension caused an access violation at the same time due to a problem with the blender .exe, the result was permanently corrupted userprefs due properties of my addon that weren't made correctly that got saved permanently into the user prefs file before it could be deleted from the reload, they were in addon preferences, pointers to property groups with i think what was a string prop missing something causing the error

i since then moved to 4.1 then 4.2 and those user prefs were eventually deleted a few days after this problem
