### ISSUE TITLE
Question: How to connect to an existing project

### ISSUE THREAD

**Issue by wadeok** [JacquesLucke/blender_vscode#159]
I'm a beginner in Blender. I just downloaded a 3D model from the internet, let's say the file name is 'project.blend'. I want to manipulate the objects inside using a Python script. As far as I know, clicking Blender Development's Blender: Start will open a new blank Blender window, but I want to open the existing 'project.blend' instead, and work with it. How can I do that?

**Comment by Mateusz-Grzelinski** [comment]
Oh my, now I might be as confused as you. 😀 
1. For quick experiments use blender built in python console. 
2. When you have experimented enough, open text editor (inside blender) and copy paste your commands there. You will need to make slight adjustments as the blender python console has some pre configuration applied. 
3. When your script is too big save it to external file and/or convert it to add-on. Only then you should start using this add-on for Vs code. 

The built in python console is your best friend in your early days

**Comment by wadeok** [comment]
@Mateusz-Grzelinski Thanks for your sharing ~ But I want to use vscode even in my early days, because vscode has many powerful features and extensions that make my coding easier.

**Comment by JuhaW** [comment]
After Blender: Start, just file/open..  your 'project.blend'. Then you'll start debugging/testing your script(s) with VSCode.

**Comment by Mateusz-Grzelinski** [comment]
I totally misunderstood you.

1. save your file as startup file: File -> Defaults -> Save Startup file
2. specify a path in arguments. Watch out for hidden spaces.
 
![image](https://github.com/user-attachments/assets/de89ee7f-922a-41b7-aed0-2c10b4d89fba)
