### ISSUE TITLE
Script works in Blender but not from Vscode

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#16]
Hi

I am writing a script that I will turn into an addon. When I run the script from Vscode I get bunch of errors. When load the exact same script in Blender text editor and run from there, it works perfectly.  Does this sound like an Vscode issue based on the logs? 

https://paste.debian.net/hidden/07afbae4/

I tried creating a script right from Vscode using the addon but I get "Cannot read property 'data' of undefined" so I just run the loaded script. It was working fine until I added obj exporting line to my code.

**Comment by JacquesLucke** [comment]
Looks like the context is not correctly initialized when using the "Run Script" command in vs code.

Thanks for the report.

**Comment by gerroon** [comment]
Thanks for looking into it.

**Comment by melMass** [comment]
This is now solved. This issue should be closed.
