### ISSUE TITLE
Custom repository for Blender 4.2 extensions

### ISSUE THREAD

**Issue by Griperis** [JacquesLucke/blender_vscode#176]
Currently the `bl_ext.user_repository` is used by default. I would ideally like to have a separate `bl_ext.vscode_dev` repository that has only the add-ons that are linked from using the extension. Can this be a customizable option?

This reduces clashes between the development environment and what you use as add-ons in production (e. g. releases without intermediate development progress).

**Comment by Griperis** [comment]
Our setup uses exactly what you mention - we have a repository and inside the repository we have folders where we point the blender env vars (using .workspace file):
- `.blender_vscode/scripts` -> `$BLENDER_USER_SCRIPTS` (and also `$BLENDER_USER_EXTENSIONS`, see note below)
- `.blender_vscode/config` -> `$BLENDER_USER_CONFIG`

I feel that one setting isn't a good solution for us - we rather do the `isolation` ourselves using other settings, and I think various developers may have various setups, so I won't enforce this.

What about an option that's optional that you can set in `vscode` config like `extension_repository_name: str`? That uses `user_default` (or `vscode_dev`) by default, and if you override it, it uses the given repo.



Another discussion point (as you mentioned the env vars) is - When you are developing for Blender 4.2 and older versions at the same time, when developing addons that are also extensions (both `bl_info` and `blender_manifest.toml`).
- Start 4.2 -> Addons are loaded as extension into the `$BLENDER_USER_EXTENSIONS`; close
- Start 3.6 -> Addons are loaded as addons into `$BLENDER_USER_SCRIPTS`
- Start 4.2 again -> you have both legacy addons from `$BLENDER_USER_SCRIPTS` and extensions from `$BLENDER_USER_EXTENSIONS`, and it creates clashes during registration of classes and operator

Not sure how to solve the latter problem.

**Comment by Mateusz-Grzelinski** [comment]
> Start 4.2 again -> you have both legacy addons from $BLENDER_USER_SCRIPTS and extensions from $BLENDER_USER_EXTENSIONS, and it creates clashes during registration of classes and operator

This is why i would like to revive #55. It needs to be adjusted after #172

> have folders where we point the blender env vars 

This is very smart, I think it deserves to be documented. in this usage `isolation` is not needed.

> custom extension_repository

Hm, 

1. `extension_repository_name` setting in VS code defaults to `blender_vscode` 
2. create this repository in blender using python API
3. make a (hard) link
4. cleanup?

Also can you take a look if #177 breaks any of your workflow?

**Comment by Griperis** [comment]
From our perspective, unlinking will help us with the problem, but I can imagine what's said in #55 is still very relevant for a lot of users.

#177 AFAIK Blender ships with its own python, and what I like about how it works now is that the extension requirements (debugpy, requests, flask) are encapsulated in the Blender installation and not in the user's directory. And the original setup works if you run vscode as admin, right? I think the change breaks existing setups, I would expect it to search the original place, and if it can't access it it could install as a fallback to the users scripts directory.

**Comment by Mateusz-Grzelinski** [comment]
> #55 

In my experimental implementation https://github.com/Mateusz-Grzelinski/blender_vscode/pull/2 I made a setting to preserve old workflow.

> #177 AFAIK

hm, so you would rather edit blender (python) system space rather than blender user space? Thats not a choice that I would make, but it worked fine for years...

> And the original setup works if you run vscode as admin, right? 

I tried it and it worked. But I think some users reported it did't even with admin

> I think the change breaks existing setups

You mean if somebody else is already using `modules` directory it we will break it? I though the whole point of `modules` folder was to have modules that can be imported?
Existing setups (when module is installed in blender python system site-packes) will continue to work fine.

**Comment by Griperis** [comment]
> ou mean if somebody else is already using

No, but the `get_package_install_directory` wouldn't return the `site-packages` folder, even if you have the right modules inside, that's what I meant. 

Otherwise I think the `modules` approach is superior from the implementation perspective. 

For us it's important that updates to the extension don't break our existing setup, but if everything can transition smoothly to the `modules` I don't see a problem in it.

**Comment by Mateusz-Grzelinski** [comment]
That is the beauty of this change: before installation there is a check:
```
If "flask" can no be imported:
    Then pip install flask
```
Site-packes is always available for python so new installation directory for does not break existing setup. 

So end user will not even notice that packages have a new installation path. 
The only downside I see is of advanced user uses custom BLENDER_USER_SCRIPTS - this will cause reinstallation of Vs code dependencies - not a big deal but a little slow down.

**Comment by Mateusz-Grzelinski** [comment]
done in #180

**Comment by Mateusz-Grzelinski** [comment]
@Griperis release in version [0.0.22] - 2024-09-04
