### ISSUE TITLE
Upgrade to version 2.0.0 to run the task: blender: blender

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#19]
Hi

I was trying to set this up on my other Win10 system and I am getting this error. I cant find what the issue is, since I do not have tasks.json file in the folder.

```
The task system is configured for version 0.1.0 (see tasks.json file), which can only execute custom tasks. Upgrade to version 2.0.0 to run the task: blender: blender```

**Comment by gerroon** [comment]
I am thinking that this is a corrupt Vscode setting issue, for the future reference if someone else has the same issue.

**Comment by JacquesLucke** [comment]
So how did you fix it? Did you install a newer version of VS Code or changed some setting?

**Comment by gerroon** [comment]
I had a back up of the Vscode settings, I restored it and the issue went away.
