### ISSUE TITLE
Extension fails to start when using "Build and Start" on master

### ISSUE THREAD

**Issue by sjkillen** [JacquesLucke/blender_vscode#190]
Working: v0.0.21
Bug: v0.0.22

Extension outputs the message "Addon starting." and its features do not function.
Running "Build and start" yields an empty menu of blender versions and the button to select a version does nothing

OS: Ubuntu 23.10 x86_64
vscode: 1.92.2

**Comment by Mateusz-Grzelinski** [comment]
Which blender version? Is it apt installed? Will take a look in following days

**Comment by sjkillen** [comment]
Ah sorry, I have a build from blender master.
I tried installing from `apt` (3.6.2) and restarting vscode it was able to initialize and launch Blender once using "build and start"
(In the "select version menu", only the apt version appeared)

On subsequent executions of "build and start", the same behavior as before and it doesn't launch.

**Comment by Mateusz-Grzelinski** [comment]
The start command will find automatically only blenders available in PATH. 
But the select window should work.
I did not test the build on master because that part of Vs code extension is not documented... 

But point taken: current master does not work.

**Comment by sjkillen** [comment]
Ah, good to know :)
The source blender build is on my PATH, and works correctly with v0.0.21 of your extension (I've reverted to that version)

**Comment by Mateusz-Grzelinski** [comment]
please check again, it might have been fixed as mentioned in #193

**Comment by sjkillen** [comment]
Works now, thanks!
