### ISSUE TITLE
Verson 0.0.22 does not populate anymore Blender executable paths from the settings.json in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by juliocargnin** [JacquesLucke/blender_vscode#195]
Hi there!

Since I reverted back to version 0.0.21 is does pick up the Blender paths in the settings.json.
But as soon as I install 0.0.22, the drop down box is always empty after every "Blender: Start" command.

I'm in POP OS 22.04 LTS.

Kind regards,
Cosmo.

**Comment by Mateusz-Grzelinski** [comment]
worked on in #193. Issue is noty obvious
