### ISSUE TITLE
Use bl_label for folder linking

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#20]
Hi

It would  be very nice if the Vscode addon actually uses the bl_label to make the symbolic links in the Blender  addon folder. At the moment it is using the folder name, and the folder names can be artbitrary or wrong during development. Obviously it would be nice if they match from the get go but that does not always happen depending on the situationm

**Comment by gerroon** [comment]
Or some kind of .json file for defining additional addon settings would be nice.

**Comment by melMass** [comment]
> Or some kind of .json file for defining additional addon settings would be nice.

More like a [Workspace Setting](https://code.visualstudio.com/docs/getstarted/settings) but I too think that's a good idea

**Comment by JacquesLucke** [comment]
I needed this myself now. This feature is available in the newest release.

The setting is called `blender.addon.moduleName`.
