### ISSUE TITLE
Cant start Blender since v0.0.22

### ISSUE THREAD

**Issue by Maxxxel** [JacquesLucke/blender_vscode#202]
Starting with version 0.0.22 i cant start Blender from VSCode anymore. I get the following error if i try:

The "to" argument must be of type string. Received undefined

**Comment by Mateusz-Grzelinski** [comment]
Can you give me more info to debug the issue? 
Blender version, is it python or TS error, your os?

**Comment by Maxxxel** [comment]
Windows 11 x64
Blender 4.0.2
Its an error shown in VSCode:
![5360a436454aaab537fed59aa3fdcf72](https://github.com/user-attachments/assets/54e7306e-f50b-4ba1-bc45-450f753f2bf7)

**Comment by Mateusz-Grzelinski** [comment]
I randomly stumbled on this error. It seems to be caused by malformatted vs code setting, but I am not sure. It is confusing as the error comes from dotnet vs code extension. 

```
 "blender.executables": [
        "sometingsomething\\blender-3.5.1-windows-x64\\blender-3.5.1-windows-x64\\blender.exe)", // -> this is ouside of list
        {
            "path": "sometingsomething\\blender-3.5.1-windows-x64\\blender-3.5.1-windows-x64\\blender.exe",
            "name": "",
            "isDebug": false
        }
    ],
```

**Comment by Maxxxel** [comment]
> I randomly stumbled on this error. It seems to be caused by malformatted vs code setting, but I am not sure. It is confusing as the error comes from dotnet vs code extension.
> 
> ```
>  "blender.executables": [
>         "sometingsomething\\blender-3.5.1-windows-x64\\blender-3.5.1-windows-x64\\blender.exe)", // -> this is ouside of list
>         {
>             "path": "sometingsomething\\blender-3.5.1-windows-x64\\blender-3.5.1-windows-x64\\blender.exe",
>             "name": "",
>             "isDebug": false
>         }
>     ],
> ```
> 
> @Maxxxel do you still have the issue? can you paste your settings?

I can confirm after i've deleted my  "blender.executables": settings, everything works again :)
