### ISSUE TITLE
Blender executables are reported as 'File not found' if using relative paths

### ISSUE THREAD

**Issue by Griperis** [JacquesLucke/blender_vscode#204]
We have following config (where everything is encapsulated to the root of the workspace):

![image](https://github.com/user-attachments/assets/9ffd5177-1236-4465-9b21-d123d3127672)

Which results in:

![image](https://github.com/user-attachments/assets/b7858847-1b25-47b1-888f-88f1089d67f1)

If I change the paths to absolute (which we don't want, so the repository is encapsulated), then it doesn't report the `File Not found` and works correctly.

Note, that **all commands work**, only the error report is incorrect.

**Comment by Mateusz-Grzelinski** [comment]
Thanks for the report, I was sure that relative paths do not work.
What is this path relative to: you can have multiple folders in your workspace - should I check paths relatoclve to all folders in workspace?

**Comment by Griperis** [comment]
It is relative to the root. We have one large workspace with multiple addons. But for vscode purpose there is only "." workspace folder defined, maybe that's the issue. (side note: that's why we introduced and use the `addonFolders` settings, otherwise typing gets messy).

I think the correct approach from how vscode works would be to check the same way the exe is searched when running the commands.

![image](https://github.com/user-attachments/assets/88d7dd09-a484-4a1e-920a-98638f4677a4)
