### ISSUE TITLE
The "Reload Addons" action sometimes does not execute

### ISSUE THREAD

**Issue by jessey-git** [JacquesLucke/blender_vscode#21]
Essentially everything works fine but at some random point using the "Reload Addons" action will do nothing. Blender is still active at this point, as-is the actual debugger connection (can set breakpoints and have them be hit).  The only way to get out of the state is to shutdown Blender and then use the "Start" action again.

I haven't been able to spot the exact pattern that triggers the issue but I'd be open to helping debug (I haven't found a good spot in the addon code to do additional tracing or checking etc)

Nothing is printed inside the Terminal pane -- usually when things work the first line printed is "Got GET: {'type': 'ping'}" but nothing will be printed when things stop working.

**Comment by JacquesLucke** [comment]
Thanks for the report. I experienced the same issue a couple of times as well.
I already worked on updating this code, but I think my latest changes are not released yet.
Should definitely work better after the next release.

**Comment by gerroon** [comment]
I also think that after a reload the addon fails to stop Blender.

**Comment by jessey-git** [comment]
Any thoughts about doing another release? I've been unable to build the extension locally myself -- some tsc compiler errors that seems to indicate bad paths or install.

**Comment by JacquesLucke** [comment]
I hope I'll get to it next week!

**Comment by JacquesLucke** [comment]
Uploaded a new release. Not sure how many of the reported problems this will fix...

**Comment by jessey-git** [comment]
Things seem much, much better now. Thank you!   I haven't seen it disconnect after a day or so now under moderate usage.  Can probably close this item.

**Comment by jessey-git** [comment]
Closing this one now

**Comment by gerroon** [comment]
I still have this issue with Blender 3.x nightly, Windows 10 VsC 1.59.1

I am not importing custom modules, only bpy. The auto reloading after save worked when I started the addon work initially after that either after save or running Reload Addons does not seem to work. Restarting VsC does not seem to help either.

Any recommendations?
