### ISSUE TITLE
Debugger does not like "from . MODULE import *"

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#22]
Hi

It seems like the debugger throws an exception if a module (from the script folder) imported like

"from . MYMODULE import *"

And throws an exception like this, when the debugger is is enabled after starting Blender

```
Exception has occurred: ModuleNotFoundError
No module named '__main__.MYMODULE'; '__main__' is not a package
  File "C:\DEV\MYADDON\__init__.py", line 41, in <module>
    from . MYMODULE import *
```

Please bear in mind that Blender runs this addon no problem and MYMODULE.py is really in "C:\DEV\MYADDON" which is where ```__init__.py```  is.

**Comment by gerroon** [comment]
I do not use a script folder not sure if I made my case clear. I am just trying to import my own library from the same folder. It is a simple Python library that I made.

**Comment by JacquesLucke** [comment]
could you make a short video of what you do exactly?

**Comment by gerroon** [comment]
Well here is a zip file with the gist of the addon. I had to trim it down since it is in progress. What is in there is how things are set up and are used

[ServerPanel.zip](https://github.com/JacquesLucke/blender_vscode/files/2729003/ServerPanel.zip)

**Comment by JacquesLucke** [comment]
Did you use the `Run Script` operator in VS Code? 
(if yes, it is not ment to work for addons)

**Comment by gerroon** [comment]
No I am not using the Run Script at all.

- I start Blender (From Vscode), so it enables the addon

- I enable Debugger using the default profile

- It throws the exception above  and the debugger kicks in

**Comment by gerroon** [comment]
Maybe I need a special debugger profile ? But this normally not an issue it seems, except in this use case of the importing

**Comment by JacquesLucke** [comment]
Ah, the second step is the problem. You don't have to enable the debugger yourself. The remote debugger should be attached to Blender automatically as soon as it starts.
The debugger you started manually will try to execute your current file outside of Blender.

**Comment by gerroon** [comment]
I see. So I am guessing that I just set up the break points and let it pick up when necessary.
