### ISSUE TITLE
Error: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by CivilVisions** [JacquesLucke/blender_vscode#24]
I get the error "Cannot read property 'data' of undefined" when attempting to launch Blender 2.8 (201901-07 00:16) on Windows 10 using the Ctrl+Shift+P: blender:start. I get the same error no matter what addon code/project I have loaded. The one shown in the attached image is the bundled MeasureIt addon by Antonio Vazquez.

When prompted for the Blender executable path, I've tried with/without quotes and other iterations with no effect. The path where I've got my 2.8 is:
C:\Users\WaschDL\Apps\blender-2.80.0-git.96f762500ef9-windows64\blender.exe

Latest VS-Code version. C/C++ and ms-python dependencies are installed.

Thanks!

![vsc error launching blender 2 8](https://user-images.githubusercontent.com/46461674/50794457-2ca7c700-1299-11e9-9546-c78c5497e746.png)

**Comment by JacquesLucke** [comment]
Thanks for the report. Will try to reproduce it!

**Comment by avatarye** [comment]
All the commands I ran resulted in this error. I am also using latest 2.80 and VS Code.

**Comment by CivilVisions** [comment]
Did a new install of the VSCode add-on today to see if I'd still get this error. It's still there on two different computers, each with the latest build of Blender 2.8 and new installs of the add-on. This is driving me nuts, because I could REALLY use this addon right now as I'm updating my 2.7x add-ons to 2.8!

I've put up a short screen capture video showing my steps: [https://youtu.be/r-I-y6I2dW4](https://youtu.be/r-I-y6I2dW4)

**Comment by JacquesLucke** [comment]
@CivilVisions, what happens when you just click on `Choose a new Blender executable...` instead of pasting a path into it?

Interesting side note, `...` is valid Python. You don't have to replace it with `pass`.

**Comment by CivilVisions** [comment]
Bingo! Selecting the executable instead of pasting in the path works and the error doesn't present! I honestly didn't know you could click the `Choose a new Blender executable...` text. I'm pretty new to using VSCode and have done all my previous development in another IDE, hence my ignorance. Thanks!

**Comment by JacquesLucke** [comment]
You don't even have to click on it, just press enter :D
Glad this is solved now, good that you made the video.
