### ISSUE TITLE
Get "Path is not Blender." when choosing executable for "Blender: Start"

### ISSUE THREAD

**Issue by dschwant** [JacquesLucke/blender_vscode#25]
Just installed latest blender Beta (blender-2.80.0-git.84c06e996a7a-windows64), and then tried to run "Blender: Start" and point to the "blender.exe" and I get "Path is not Blender.". Is this related to the version of blender (since this Extension was built before the Beta release?) or something else?

**Comment by elliotwoods** [comment]
Same here - thought i just needed to take it out of `Program Files` (for permissions) - but also need to remove any spaces from the path names (e.g. `c:\Blender\Blender 2.8` won't work).

**Comment by dschwant** [comment]
Yes, I went and moved the 2.8B code to a non-space path, and it does not complain now but it also does not start Blender when I do a "Blender: Start". This is what I have now and running the "C:\\..." from a DOS prompt does launch Blender:

"blender.executables": [ { "path": "C:\\Blender2_8B\\blender.exe" } ]

I don't have the time to figure that out, so I will try and get from this extension what I can without that working.

**Comment by Ldash4** [comment]
Same issue presen on OSX. Making a symbolic link to a filepath without spaces (`/usr/local/bin/blender`) did not appear to work either.

**Comment by draguu** [comment]
got it working , changed my main blender folder name to "newblender" and changed blender executable name to'blender2.8'
so my old path was
>  " /home/weybec02/Downloads//blender-2.80-6439ed844e78-linux-glibc224-x86_64/blender"

and my new path is 
> /home/weybec02/Downloads/newblender/blender2.8

**Comment by JacquesLucke** [comment]
This should be fixed by now. Please create a new report, if the problem persists.
