### ISSUE TITLE
Blender:Start issues on Windows 10

### ISSUE THREAD

**Issue by maybites** [JacquesLucke/blender_vscode#31]
When trying to start blender via VS Code I get the following error: 

blender starts up but crashes after a few seconds:

> Executing task: c:\Program Files\Blender Foundation\blender-2.80.0\blender.exe --python c:\Users\maybites\.vscode\extensions\jacqueslucke.blender-development-0.0.11\pythonFiles\launch.py <
```
Read prefs: C:\Users\maybites\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: c:\Program Files\Blender Foundation\blender-2.80.0\2.80\python
c:\Program Files\Blender Foundation\blender-2.80.0\2.80\python\bin\python.EXE: No module named pip.__main__; 'pip' is a package and cannot be directly executed

################################################################################
>   could not install ptvsd
################################################################################

Saved session recovery to 'C:\Users\maybites\AppData\Local\Temp\quit.blend'
The terminal process terminated with exit code: 1
```

**Comment by JacquesLucke** [comment]
Can you check if the same problem happens when you use the portable Blender version? (not the installer)
Or did you copy Blender into the `Program Files` folder manually?

Unfortunately, I don't know what causes this error yet.

**Comment by maybites** [comment]
I installed it manually from the [zip](https://builder.blender.org/download/blender-2.80-6fd11a21f5c5-win64.zip)

but before I failed with the above issue, I had to set the security access to the python-folder inside the 2.80 folder

I also added the 'pip'-folder inside python/site-packages

strangely on a different win10 machine I was able to make your script work by simply changing the security access to the 'python'-folder. (without adding the pip folder manually).

maybe its a security access issue? I will investigate further..

**Comment by pwrman64** [comment]
Got the same issue here.

**Comment by OlafHaag** [comment]
I just unpacked the blender 2.8 archive into my downloads folder and not into windows' programs folder. Blender starts from VS Code without problems. It installed pip, ptvsd and flask.

**Comment by markbehm71** [comment]
Same, @OlafHaag . 
**Having a copy of my blender 2.80.0 directory in my win10 Downloads folder allowed everything to work smoothly without permissions issues**. Prior to this I couldn't get it running at work or home no matter what permissions I tried to force on things.  I am guessing any public win folder would do it.

**Comment by postvak** [comment]
I got the same issue. For me it was solved by starting VS Code as administrator.

**Comment by Zorobay** [comment]
I had the same issue. Can confirm that running VS Code as admin solved the problem 👍

**Comment by markbehm71** [comment]
if you use a copy of blender that lives in a public spot (my Documents or downloads, etc) you should be fine. I've not had an issue since.

**Comment by Codelito** [comment]
hey, thank you. running vscode as admin sorted it out.

**Comment by paulb5352** [comment]
Running as Admin worked for me as well, thanks Zorobay

**Comment by Sam54123** [comment]
Are you sure running VSCode as admin is a good idea? Given the nature of how it loads 3rd party extensions, that could be a major vulnerability.

**Comment by markbehm71** [comment]
> Are you sure running VSCode as admin is a good idea? Given the nature of how it loads 3rd party extensions, that could be a major vulnerability.

That was my worry. Dropping a copy/link of whatever Blender vers I need into Documents felt safter. Still working for me.

**Comment by Sam54123** [comment]
> That was my worry. Dropping a copy/link of whatever Blender vers I need into Documents felt safter. Still working for me.

How do you do that? My copy is having trouble accessing %appdata%, which is immovable to my knowledge.

**Comment by markbehm71** [comment]
> > That was my worry. Dropping a copy/link of whatever Blender vers I need into Documents felt safter. Still working for me.
> 
> How do you do that? My copy is having trouble accessing %appdata%, which is immovable to my knowledge.

Sorry - I mean I have a copy of **Program Files/Blender Foundation/blender-2.91** (as well as 2.83) into my **Documents** folder, which is more permissive folder in Windows. You have to point the VSC plugin prefs to that location. My development folder (actual addons or scripts) is elsewhere - in my case not in my config/ folder. It's location doesn't seem to matter as I believe the plugin is taking care of a linked copy in the appropriate spot.

**Comment by zNightlord** [comment]
I have the same issue but only for 2.83.12
It was fine for 2.83.9 or 2.83.10 after this happen. But I didn't noticed what really happpened. 
2.80, 2.91 run fine. run VSCode as admin or moving the folder elsewhere don't fix the problem. 

```Read prefs: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: d:\Blender\blender-2.83-windows64\2.83\python
unknown argument, loading as file: -m
Error: Cannot read file 'd:\Blender\blender-2.83-windows64\-m': No such file or directory
Error: argument has no '.blend' file extension, not using as new file, exiting! d:\Blender\blender-2.83-windows64\-m
Saved session recovery to 'C:\Users\Admin\AppData\Local\Temp\quit.blend'

Blender quit

################################################################################
>   could not install ptvsd
################################################################################

Saved session recovery to 'C:\Users\Admin\AppData\Local\Temp\quit.blend'
The terminal process "d:\Blender\blender-2.83-windows64\blender.exe '--python', 'c:\Users\Admin\.vscode\extensions\jacqueslucke.blender-development-0.0.14\pythonFiles\launch.py'" terminated with exit code: 1.```

**Comment by 3DHerbie** [comment]
I found another solution since running as administrator or changing the directory didnt do the job for me either.

Solution 1 (tested with Blender 2.80rc3 zip extracted, "Program Files/Blender Foundation" folder):
Open vs Code
Install Blender Development version 0.0.12
Then do "Blender:start"
Opened fine with Addon
Now change back to version 0.0.14 -> Still working

Solution 2 (tested with Blender 2.80 msi installer, also "Program Files/Blender Foundation" ):
Do the same just start vs Code as administrator.

I hope this fixes the issue for other people. 
Also this should be good information for bugfixing.

**Comment by Mateusz-Grzelinski** [comment]
closing as ptvsd is no longer used and blender 2.80.34 is pretty old. This isssues will no longer occur after 177 is done
