### ISSUE TITLE
looks super cool

### ISSUE THREAD

**Issue by matt-erhart** [JacquesLucke/blender_vscode#4]
I've always been interested in using blender as a cool way to teach programming, but the code->blender flow never worked well. I hope something like this can become standard practice, so bug the devs to add this to the official blender docs.

**Comment by JacquesLucke** [comment]
Does it actually work for you? I still did not get feedback from anyone haha
Only tried on my own machine so far..

But yes, after some testing I'll task them if I can link to this project from the official Blender docs.
