### ISSUE TITLE
How to use with multiple addons?

### ISSUE THREAD

**Issue by NickGlenn** [JacquesLucke/blender_vscode#46]
I have a single repo/workspace that contains multiple Blender addons.  When I run the "Build & Start" command it doesn't seem to load up any of them.   Is there currently a way to use the extension for this scenario?

If not, a useful feature might be a workspace/project setting to manually declare entry points  for addons.  That way you could mount and load multiple addons or select which addon to mount when running "Build & Start".

**Comment by JacquesLucke** [comment]
Hm that is probably not supported currently. Are the addons in separate folders?

**Comment by NickGlenn** [comment]
Yes, they are currently in separate folders under a master `addons/` folder.  So the structure is...

```
addons/
  plugin_a/
    __init__.py
  plugin_b/
    __init__.py
  plugin_c/
    __init__.py
```

**Comment by JacquesLucke** [comment]
Does it work when you load these folders separately into vscode?

**Comment by NickGlenn** [comment]
Yes it does, and that's what I've been doing for the time being.  Part of why it'd be nice to launch specific plugins from the root is that the documentation/site files for the plugins are in another folder at the top level (sibling to `addons/`), which means I need another window open for editing the site and documentation for the addons.  Additionally, context switching between addons also means independent VSCode windows that I'd need to hop between.

I do realize that I'm likely the minority of users with this pattern, but it might be a useful consideration for others who have mono repo projects or who manage related addons under an umbrella project.

Great work on this extension by the way!

**Comment by JacquesLucke** [comment]
Visual Studio Code supports multi-root-workspaces (https://code.visualstudio.com/docs/editor/multi-root-workspaces). With that, you do not need to have multiple instances running at the same time. The blender extension should be able to support that, never really tried though.

**Comment by NickGlenn** [comment]
I tried that approach as well.  If only one addon is present in any of the listed folders for the workspace, it works.  When an addon exists in more than one folder listed in the `*.code-workspace`, it fails to load any of them.

**Comment by Griperis** [comment]
Use _**folders**_ settings in _**.code-workspace**_ file as follows:
`
{
	"folders": [
		{
			"path": "addon1"
		},
		{
			"path": "addon2"
		},
        ]
...
}
`

All folders have to contain the **\_\_init\_\_.py** file, which is this extension looking for.
