### ISSUE TITLE
Attaching / debugging doesn't work

### ISSUE THREAD

**Issue by benthillerkus** [JacquesLucke/blender_vscode#48]
I can see the console logs inside VS Code and when I close Bledner the tasked in VScode in being closed too, so they are connected. Breakpoints don't work though

I have no clue what is causing this, because I know it worked at some point.
Currently I have my project opened in VSCode and the folder with add-on is linked inside my current blender versions script folder via a junction.
I'm running Windows 10 1903, the latest version of your add-on, vs-code and the newest build bot build of blender.

**Comment by ogierm** [comment]
Are there some kind of logs or additional information that I could add?

**Comment by ogierm** [comment]
Hmm... So I moved the folder of my blender installation remvoed all junctions, set the correct paths and the add-on actually worked.
I then terminated the session with the red plug icon, and after that debugging stopped working on subsequent runs. Again: your add-on has no trouble creatin the symlink, loading the add-on, creating a debug session and loading itself into blender, it's jsut that debuggin doesn't work.

**Comment by jaxxtrend** [comment]
Your addon need be placed in blender addon folder, like a "...\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\" Otherwise this extension create link to the place your addon and this work fine in first look, but breakpoints not working. =/

**Comment by ZapUser77** [comment]
I'm having a similar problem.
It never enters the body of code.
Breakpoints inside the main body never execute, breakpoints in the "import" section work... and step through the code, and it just skips over everything inside "def".

**Comment by Mateusz-Grzelinski** [comment]
Closing as stale issue.
Please remember that the because this is remote debugging some breakpoint in global scope might be missed by debugger (no easy fix for that).
