### ISSUE TITLE
VSCode for Blender development

### ISSUE THREAD

**Issue by H-G-Hristov** [JacquesLucke/blender_vscode#50]
This extension is for addon development?
What about using VSCode to develop Blender C++/Python itself? Since VSCode could use CMake projects directly via this extension: https://github.com/microsoft/vscode-cmake-tools it looks that VSCode could be all in one solution for Blender development especially because it support all platforms that Blender runs on.

**Comment by JacquesLucke** [comment]
This extension is mostly for addon development. 
Personally, I also use it for Blender Core development, but I don't expect that this works for others in the current state.

You don't really need this extension for core development.

**Comment by Celeborn2BeAlive** [comment]
> This extension is for addon development?
> What about using VSCode to develop Blender C++/Python itself? Since VSCode could use CMake projects directly via this extension: https://github.com/microsoft/vscode-cmake-tools it looks that VSCode could be all in one solution for Blender development especially because it support all platforms that Blender runs on.

The Blender wiki has a great guide for setupping a VS code environmement for Blender code dev: https://wiki.blender.org/wiki/Developer_Intro/Environment/Portable_CMake_VSCode
You also need to follow this tutorial https://wiki.blender.org/wiki/Building_Blender/Windows to have the VS compiler and debugguer, but you don't even need to install the Visual Studio editor if you just want to focus on editing in VS code.

**Comment by Diana271** [comment]
I am new to Blender application, however I am experienced in visual studio C# .net programming. I have an automation application in .net which I want to merge with Blender and create an interactive 3D application. Is it possible to merge both VS C# with Blender?

**Comment by Mateusz-Grzelinski** [comment]
Sorry this question is way  outside of my expertise.
Closing as stale issue.
