### ISSUE TITLE
"Blender: New Addon" fails silently after "Choose Template" prompt is answered

### ISSUE THREAD

**Issue by mg0536** [JacquesLucke/blender_vscode#54]
When executing the "Blender: New Addon" tool, I answer the prompt "Choose Template", and the tool stops. I can't find any log, or debugging information.

I may have installation issues (3 different python distributions, including Blender), but the most important problem I'm experiencing is that I'm not finding troubleshooting information in VSCode, for this Addon.

**Comment by Mateusz-Grzelinski** [comment]
I have used this command recently and did not find this problem. Please check with newest versions of extension.
Please reopen if the issue presissts.
