### ISSUE TITLE
Set Python Environment correctly?

### ISSUE THREAD

**Issue by snovak** [JacquesLucke/blender_vscode#57]
Awesome plugin! Thank you! 

I'm trying to set the Python env to Blender's bundled path, so all the Blender specific site-packages are available (i.e.- import bpy).  

For example, if I try changing the VSCode Python Interpreter to the bundled Blender exe C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\bin\python.exe, it doesn't stick in VSCode. 

What am I missing?

**Comment by clankill3r** [comment]
I had the same, restart VSCode and it will show up.

**Comment by Mateusz-Grzelinski** [comment]
it needs some time and restarts and it shows up.
