### ISSUE TITLE
Feature request: Custom command line arguments

### ISSUE THREAD

**Issue by malte-v** [JacquesLucke/blender_vscode#58]
It would be really useful to me if we could specify additional command line arguments for Blender, like the --debug* ones. I was thinking of adding an array of strings for the arguments in the settings.

**Comment by andgeno** [comment]
I could also use a feature to pass some additional arguments to Blender on startup.

**Comment by MBetters** [comment]
Also, it'd be great to be able to pass args to scripts run by `Run Script`.

**Comment by s-suraj-08** [comment]
Is there any update on how to pass CLI to my python script?

**Comment by Mateusz-Grzelinski** [comment]
| I could also use a feature to pass some additional arguments to Blender on startup.

use vs code setting `blender.additionalArguments`

| Is there any update on how to pass CLI to my python script?

read `blender --help`. use `--` and `blender.additionalArguments`
