### ISSUE TITLE
Wiping addon preferences on reload

### ISSUE THREAD

**Issue by stolliemods** [JacquesLucke/blender_vscode#59]
When using the "Blender: Reload Addons" command from within VS code it keeps wiping the user preferences for the addon I'm working on. Confirmed this on two different addons.

Workaround: 
Close blender entirely and use Blender: Start. Preferences remain intact.

**Comment by Mateusz-Grzelinski** [comment]
Do you realize that you need to actually save the preferences? 
Yes, when you close Blender and have auto-save preferences checked, the preferences will be automatically saved...
