### ISSUE TITLE
How to clean uninstall?

### ISSUE THREAD

**Issue by Flavelius** [JacquesLucke/blender_vscode#69]
Hey, 
i tried using this tool, but it resulted in a lot of errors and strange behaviour inside blender (couldn't find my addon, debugger couldn't connect, blank black 0px console window with no output and a lot of python errors)
Plain single file addon worked fine, i wanted to have debugging, but after this unfortunate mess i want to go back to just going the dumb way.
It seems Blender:Start installs and configures a bunch of extra stuff that i now want to be removed and reset again, how do i do that?

**Comment by JacquesLucke** [comment]
I should really just create a link in Blender's addon directory. You have to remove it from there. When you open Blender normally, it should work as expected if I remember correctly. Please try that.

**Comment by Flavelius** [comment]
Thanks for the fast reply; i went through the files to see what was installed automatically and as far as i see it _init_.py declares 3 python modules as required to be present, so those are probably what i saw being installed.
I'm not sure what you mean with removing 'it' from blenders directory, can you elaborate more on that?

**Comment by JacquesLucke** [comment]
You're right. Those packages have been installed as well. They should not affect anything in Blender.
Glad your issue is solved.
