### ISSUE TITLE
Blender: Start - cannot select Blender executable (Linux)

### ISSUE THREAD

**Issue by fsoft72** [JacquesLucke/blender_vscode#7]
Hello,

I cannot select the Blender Executable, when I select "Blender: Start" from the prompt, the requester that appears does not allow me to move on the file system, and the Blender I have in my path is not shown.

I am on Linux (KUbuntu 18.04) with the latest stable VSCode and latest Blender 2.80 beta

I have attached a small mp4 video showing exactly what happens on my machine.

[blender-vscode.zip](https://github.com/JacquesLucke/blender_vscode/files/2638790/blender-vscode.zip)

**Comment by fsoft72** [comment]
Hi Jacques,
setting the configuration manually works like a charm :-)
And this extension really rocks!! Keep the good work! :+1: 

BTW: is there a way to have VSCode autocompletion on bpy module methods and commands?

Thanks a lot

**Comment by JacquesLucke** [comment]
Yes, the extension will support (limited) autocompletion in the future. I want to implement that within this month.

**Comment by aldebaran798** [comment]
@JacquesLucke you hear about this addon? [https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_visual_studio_code.md](url) 
Great work!

**Comment by JacquesLucke** [comment]
I actually did not know this specific project yet. Thank you.

**Comment by JacquesLucke** [comment]
I did not have this problem in the last few months. Closing this for now. It can be reopened when the problems comes back.

**Comment by ViopAl** [comment]
s
