### ISSUE TITLE
Do not ask for Blender executable path if it is in %PATH%

### ISSUE THREAD

**Issue by TomasHubelbauer** [JacquesLucke/blender_vscode#71]
Hi! I just started using this extension and I'd like to recommend and improvement which I think could be worthwhile: If Blender is in %PATH%, do not ask for the Blender executable path and use the one from path, or offer the Blender executable found in path as another option in the VS Code prompt shown after the Blender: Start command is executed for the first time.

I'll be interested in hearing what you think about this suggestion. The ###BLENDER_TEST### check should probably be done on the %PATH% executable just in case it isn't Blender and if the %PATH% Blender fails this check, the flow would fall back to the old one.

Let me know what you think, I'll be happy to work on this if you like the idea!

**Comment by Mateusz-Grzelinski** [comment]
Thats what I was playing around in https://github.com/JacquesLucke/blender_vscode/pull/179
Doing the ` ###BLENDER_TEST### ` might be pretty slow though, and i am wodering about caching...
Feel ffree to commend on PR.

**Comment by Mateusz-Grzelinski** [comment]
feature was released in version [0.0.22] - 2024-09-04, but some improvements can be made as described in #185
