### ISSUE TITLE
Remove some of the log messages

### ISSUE THREAD

**Issue by MatthiasThDs** [JacquesLucke/blender_vscode#74]
Just a short question, when i reload my Addon from Visual Code, i get some log messages such as

```
sending: {'type': 'enableFailure'}
Got GET: {'type': 'ping'}
Got POST: {'type': 'reload', 'names': ['XXX']}
addon_utils.disable: XXX not disabled
```

Can I somehow remove those logs? I dont like them :)

**Comment by JacquesLucke** [comment]
Unfortunately, that is not possible right now without modifying the extension itself (you can do that of course).
