### ISSUE TITLE
No module named 'bpy'

### ISSUE THREAD

**Issue by devinvenable** [JacquesLucke/blender_vscode#83]
I've tried running new scripts after starting blender with Blender:Start.  Console reports:
```
devin@devin-OEM:~/src/blender/scripts$ /usr/bin/python3 "/home/devin/src/blender/scripts/script b93273088e.py"
Traceback (most recent call last):
  File "/home/devin/src/blender/scripts/script b93273088e.py", line 1, in <module>
    import bpy
ModuleNotFoundError: No module named 'bpy'
```
Must I use a version of Blender I've built from scratch? I'm using version 2.91 that was installed on my Ubuntu machine previously.

**Comment by Mateusz-Grzelinski** [comment]
It will not work. You must use VS code command `Blender: Run Script`
