### ISSUE TITLE
How to set blender.executables on Windows? 

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#84]
Hi

Can anyone tell me the right way to set this in the settings on Windows? I cannot make it work , whatever I tried

`"blender.executables": [ {"path": C:\\blender\\blender.exe, "Blender Release": "", "isDebug": false}]`

When I try to add the path with after running `blender start` then putting the path I get this `Cannot read property 'data' of undefined`

thanks

**Comment by Nullmatic** [comment]
Try putting quotes around the path and change `"Belnder Release"` to `"name"`, so it will look like this: 

`{"path": "C:\\blender\\blender.exe", "name": "", "isDebug": false}`

See if this works for you.
