### ISSUE TITLE
blender.start 'not found' in VS Code

### ISSUE THREAD

**Issue by fsoft72** [JacquesLucke/blender_vscode#88]
Hello,

when I launch "Blender: Start" from command palette, I get the error in the attachment (command 'blender.start' not found).
There is not output in DEBUG CONSOLE or OUTPUT.

What can I check?

I am using:

- blender 2.91
- VS Code 1.53.2

![blender](https://user-images.githubusercontent.com/2844375/107930388-36717d80-6f7b-11eb-9525-10a7b7d19e5e.jpg)

**Comment by theres1** [comment]
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.1.7601


Blender Development 0.0.16

I noticed this problem after recent VS Code update. I get this error message in the form of a system pop-up (not a VSCode pop-up).

**Comment by SuzukaDev** [comment]
I have the same problem (Blender Development 0.0.18, and also with 0.0.17 (VSCodium)

**Comment by theoryshaw** [comment]
same problem
Blender Development [0.0.19] - 2023-12-05
VSCodium Version: 1.85.1

**Comment by theoryshaw** [comment]
same problem
Blender Development [0.0.19] - 2023-12-05
VSCodium Version: 1.85.1

**Comment by theoryshaw** [comment]
VSCodium eventually prompt me to download/install ms-vscode.cpptools and it seemed to work after that. Not sure it was related.

**Comment by Mateusz-Grzelinski** [comment]
yes, that was most likely the issue. This extensions has dependency on cpp and python extensions.
