### ISSUE TITLE
AttributeError: module 'ptvsd' has no attribute 'enable_attach'

### ISSUE THREAD

**Issue by marwie** [JacquesLucke/blender_vscode#89]
Getting this error when trying to start.
Tried using python 3.x and 2.7.x

When returning in communication.py blender starts, reload plugin works as well but hot reload does not

![image](https://user-images.githubusercontent.com/5083203/108505695-15c96080-72b8-11eb-8eec-08898c345a60.png)

**Comment by Mateusz-Grzelinski** [comment]
closing as stale. We are no longer using ptvsd.
