### ISSUE TITLE
blender executable not accepted 

### ISSUE THREAD

**Issue by Lynchon83** [JacquesLucke/blender_vscode#9]
I'm trying to open launch blender within vscode but an error pops up telling me the path is not blender, is very weird as it didn't happen in my other computer with same software versions: windows 10, python 3.7, and latest versions of vscode and blender 2.80.

**Comment by JacquesLucke** [comment]
In that case my simple blender-check probably failed..
What is the path to your executable?

Can you test what the output of this command is?
`BLENDER_PATH --factory-startup -b --python-expr "import sys; print('###TEST_BLENDER###'); sys.stdout.flush(); sys.exit()"`

**Comment by Lynchon83** [comment]
I've read previous bug reports, and I'm getting same error after specifying manually blender's path:

```
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.
```

**Comment by Lynchon83** [comment]
```
+ CategoryInfo          : ObjectNotFound: (BLENDER_PATH:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by JacquesLucke** [comment]
instead of `BLENDER_PATH` you have to insert the path to the executable

**Comment by Lynchon83** [comment]
ok, that was stupid, sorry I'm new to coding. 

The path should be inbetween ""? because I'm getting same error

**Comment by JacquesLucke** [comment]
If you have spaces in your path, you have to put quotes around it. Please show me a screenshot of what you are doing.

**Comment by Lynchon83** [comment]
![captura](https://user-images.githubusercontent.com/45634961/49530352-5c3d6b00-f8b8-11e8-893b-c6deb17c0395.JPG)

**Comment by Lynchon83** [comment]
I do have spaces in my path

**Comment by JacquesLucke** [comment]
What happens when you use a terminal outside of VS Code, and without the extra arguments? (so just the path to Blender)

**Comment by Lynchon83** [comment]
![captura](https://user-images.githubusercontent.com/45634961/49530610-dcfc6700-f8b8-11e8-9013-44b28a9706ce.JPG)

**Comment by Lynchon83** [comment]
from cmd blender launches normally

**Comment by JacquesLucke** [comment]
show me what you type into cmd to make it launch normally

**Comment by Lynchon83** [comment]
"C:\Users\Juan Manuel Lynch\Downloads\blender-2.80.0-git.1fa527bfa3a-windows64\blender.exe"

**Comment by JacquesLucke** [comment]
ok, I'll have to test this myself a bit later of tomorrow. Could you try to copy Blender into a path that has no spaces in it?

**Comment by Lynchon83** [comment]
ok, that did solve the problem. spaces in the path where causing the problem. Thanks for your patience,

**Comment by hedgehog90** [comment]
My blender is located in "C:\Program Files\Blender Foundation\Blender\blender.exe" and it also fails with "Path is not Blender" when I try to select it in VS Code.

**Comment by JacquesLucke** [comment]
ok, I guess the cause of that is exactly the same.
For now the fix is just to move the Blender folder into some directory that has no spaces in the path.

(Looks like you use a version of Blender that has to be installed. I recommend you to download one of the .zip files which don't need to be installed.)

**Comment by hedgehog90** [comment]
Ok, but the fix looks incredibly simple, just put double quotes around ${filepath} on line 167 of blender_executable.ts and re-submit to VS Code Marketplace.

**Comment by JacquesLucke** [comment]
That is probably right. Will do it when I work on it again..
Feel free to make a pull request!
