### ISSUE TITLE
Looks like "Gizmo" and "GizmoGroup" were accidentally removed from auto_load.py in 0.0.13

### ISSUE THREAD

**Issue by jessey-git** [JacquesLucke/blender_vscode#91]
This would prevent folks from registering their custom gizmos correctly if they use the new auto_load.py as a template.

https://github.com/JacquesLucke/blender_vscode/commit/3296275f2bdf2e382f8f7106fea149c4e9be5838#diff-9738ac67607466100291c17470c593209a6ad718a574d0903d9eb2e8b0a33727

**Comment by JacquesLucke** [comment]
Thanks. Should be fixed in 0.0.14.
