### ISSUE TITLE
Breakpoints ignored in imported modules

### ISSUE THREAD

**Issue by fomaamof** [JacquesLucke/blender_vscode#97]
While debugging only breakpoint set in `__init__.py` cause stop.
All breakpoints set in imported modules are ignored.
Where can I look for a solution?

**Comment by Mateusz-Grzelinski** [comment]
related #140 also disable `"debugpy.debugJustMyCode"`. You need to be very careful to check if the file you are using to debugging is actually imported. Check it using `__path__`:
```
>>> import debugpy
>>> debugpy.__path__
```
