### ISSUE TITLE
 could not install debugpy

### ISSUE THREAD

**Issue by Daksitha** [JacquesLucke/blender_vscode#98]
Blender quit/crash after initial start up

**Comment by auzmartist** [comment]
In my case, this was resolved by running vscode as administrator (in Windows).

**Comment by JacquesLucke** [comment]
I'll keep track of the issue in #99, thanks for the report.

**Comment by derrick-xwp** [comment]
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\\\AppData\\Local\\Temp\\pip-target-q6ze2ji3\\lib\\python\\debugpy' -> 'f:\\Program Files\\Blender Foundation\\Blender-2.92\\2.92\\python\\lib\\site-packages\\debugpy'

During handling of the above exception, another exception occurred:


run as admin dose not help me
